# Generated by Django 5.1.2 on 2024-11-17 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_text',
            field=models.TextField(help_text='Enter the details of your complaint.'),
        ),
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_purchased', models.CharField(max_length=255)),
                ('issue_faced', models.TextField()),
                ('file_upload', models.FileField(upload_to='grievances/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
